#!env/bin/python
import argparse
import constants as c
import algorithms

parser = argparse.ArgumentParser(prog=c.name, description=c.description, epilog=c.epilog)
parser.add_argument('type', choices=['cipher', 'decipher'], help=c.help['type'])
parser.add_argument('-p', '--password', required=True, help=c.help['password'])
parser.add_argument('--salt', required=True, help=c.help['salt'])
parser.add_argument('--size', required=True,
                    choices=[128, 192, 256], type=int, default=128, help=c.help['size'])
parser.add_argument('-i', '--input', required=True, help=c.help['input'])
parser.add_argument('-o', '--output', required=True, help=c.help['output'])

args = vars(parser.parse_args())

key = algorithms.generateKey(args['password'], args['salt'], args['size'])

if args['type'] == 'cipher':
  algorithms.cipher(args, key)
if args['type'] == 'decipher':
  algorithms.decipher(args, key)
